[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_pdas = "4ceG76xQbYtpDb2zPc7usRrgKBzYbtTJedGrtZXRcGzm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/gaylonalfano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
